### PR TITLE
[release/v0.1.1] Update publishing workflows to use PATs with fine-grained access control

### PR DESCRIPTION
**Pull request by jdbaldry**
(cherry picked from commit 9c283be9cf26ee816cdb6f3812882d1e74580574)

### CODE REVIEW

**Comment by simonswine** [comment]
I am unsure, if I should have created a release/v0.1.1 branch when releasing in December. There are some fixes that need to be done to make the CI happy

**Comment by jdbaldry** [comment]
If you are not rushing to publish docs from this release branch, we can close this.

Otherwise, I can spend some time looking into the CI fixes :)

**Comment by jdbaldry** [comment]
Oh wait, I re-read your comment and understand that you are talking about a release that has happened more recently. 

I think because of https://github.com/grafana/phlare/blob/5ee30e9f19abf84bded79bc83b6c04b5054faf71/.github/workflows/publish-technical-documentation-release.yml#L48 we decided to have long lived release branches for patches too which would suggest we should backport this to a `release-v0.1.1` if it existed.

If the above is correct, I should close this and we should decided whether we want to create that long lived release branch and backport there instead.

**Comment by simonswine** [comment]
@jdbaldry yes I have retrospectively created the release branch and rebased your commit ontop if it. Let's see what the CI gods say

**Review by simonswine — APPROVED** [review]
LGTM

From my point of view this can be merged, I leave it to you @jdbaldry to click the button :muscle:

**Comment by jdbaldry** [comment]
Thanks bud!

**Comment by jdbaldry** [comment]
I actually can't hit merge because I don't have write access to the repository

**Comment by cyriltovena** [comment]
done !

**Pull request merged**
