### PR TITLE
Add index page

### PR DESCRIPTION
**Pull request by hi-rustin**
close https://github.com/grafana/phlare/issues/508

It looks like:
image

### CODE REVIEW

**Comment by hi-rustin** [comment]
@cyriltovena What kind of index I should add a link for? Do we need to list all the HTTP routes?

**Comment by cyriltovena** [comment]
Love the work btw ! well done @hi-rustin

**Comment by hi-rustin** [comment]
> Those could be nice:
> 
> * /runtime_config
> * /api/swagger.json

Added. 
Thanks for your review!  💚 💙 💜 💛 ❤️

> 'd love to have statusv1.StatusServiceServer but I think this will require javascript or another handler, so this could be done in another PR.

I'll try to add it next PR.

**Review by cyriltovena — APPROVED** [review]
LGTM

**Pull request merged**
