### PR TITLE
chore(pyroscope): add /ingest path

### PR DESCRIPTION
**Pull request by korniltsev**

### CODE REVIEW

**Comment by eh-am** [comment]
@korniltsev what are the motivations for this?

**Comment by korniltsev** [comment]
@eh-am unified ingestion path for both phlare and pyroscope - just use /ingest. I left /pyroscope/ingest because some guys already remote-writing/pushing there.
With a unified ingest path /ingest It is going to be easier to document and integrate pyroscope agents pushing to phlare, because there will be no exceptions, like "if you ingest to pyroscope - use / and if you ingest to phlare use /pyroscope"

**Review by simonswine — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
> go for it @hi-rustin and we'll close this one.

Added! Thanks!

**Pull request closed without merging**
