### PR TITLE
Refactor all APIs to a better structure

### PR DESCRIPTION
**Pull request by hi-rustin**
close https://github.com/grafana/phlare/issues/587
close https://github.com/grafana/phlare/pull/637

Adapt the gzip support from Mimir as well.

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
Need to resolve the conflicts and move more grpc APIs into api.go.

**Review by cyriltovena — APPROVED** [review]
LGTM 

Why do we fork gzip ?

**Comment by hi-rustin** [comment]
> Why do we fork gzip ?

Do you ask why we copy the gizp code or why we add gzip support?

From the comment:
```go
// Package gziphandler mirrors the package github.com/nytimes/gziphandler
// until https://github.com/nytimes/gziphandler/pull/112 is merged.
// Once it's merged, we can delete it from here and switch back to using that one.
```

**Comment by hi-rustin** [comment]
Tested it locally:
image

**Review by hi-rustin — COMMENTED** [review]
Self check

**Pull request merged**
